### ISSUE TITLE
New privacy options

### ISSUE THREAD

**Issue by kfarwell** [rovrlabs/rovr#21]
- [x] Show your profile link on the profiles of people you invite? (only during beta)
- [x] Who can see your bio?
- [x] Who can see your VR platform?
- [x] Who can see friends they have in common with you?
- [x] Who can see community groups you're a member of?
- [x] Opt-out of anonymous statistics?
- [x] Port to onboarding
- [x] Port to guest list & notifications

**Comment by kfarwell** [comment]
@anthony-ft 
1. needs testing
2. what should the defaults be? thinking `yes`, `public`, `public`, `friends only`, `rovr users`, `no`

**Comment by anthony-ft** [comment]
Yes, public, ROVR users, [ROVR users can see # of mutual friends, friends can see actual friends usernames], Friends only [no one should be able to see the private groups you're a part of unless you're both in them], no.

Let's phrase as "mutual friends" and "mutual community groups"

**Comment by kfarwell** [comment]
@anthony-ft 

> [ROVR users can see # of mutual friends, friends can see actual friends usernames]

I'm going to call this "friends only". OK?

The three options:
1. "Anyone on ROVR" -> registered users can see your mutual friends
2. "Friends only" -> registered users can see how many mutual friends you have, friends can see who they are
3. "Nobody" -> obvious

> Friends only [no one should be able to see the private groups you're a part of unless you're both in them]

These are the options I currently have implemented:
1. "Anyone on ROVR" -> registered users can see your name in group directories, and can see *mutual groups only* on your profile
2. "Other group members only" -> users in a particular group that you're in can see your name in that particular group's directory and can see that particular group on your profile

If follows naturally that no one will ever see your private groups without at least having their secret invite links.

What does "friends only" entail, precisely?

> Let's phrase as "mutual friends" and "mutual community groups"

These are displayed next to "shared traits"... should this be "mutual traits" to match or still "shared"?

**Comment by anthony-ft** [comment]
"Friends only" sounds for the first sounds good. 

"Other group members only" makes sense given same group. I meant that people can only ever see the groups you share in common, never the full list of groups you have, public or (as is already implemented) private.

No changes to "shared traits".

**Comment by kfarwell** [comment]
Removed group preference (if you can see a group page you can join it, doesn't really make a difference).
