### ISSUE TITLE
Displaying new to VR

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#25]
> rovrfan42 is new to VR. Give them some tips, or show them around!
- this should display above in an orange or blue text box i.e.  "join the waitlist" text
- needs more indication that's its separate from bio; perhaps as italiscized?
- or a "new to VR" blue tag, with help text after before or after shared traits

**Comment by kfarwell** [comment]
I think the separated box is visually confusing in contexts which display more than one profile in a row, especially wave notifications which already have such a box.

The floating tag seems a bit out of place to me, and loses the call to action.

Leaning towards italics.

![image](https://user-images.githubusercontent.com/4172356/131233630-374f354e-ea0e-4fe9-ad6a-7cabbdbaa850.png)
![image](https://user-images.githubusercontent.com/4172356/131233631-b235a419-7329-4815-9eaa-54941f5b9653.png)
![image](https://user-images.githubusercontent.com/4172356/131233632-8ffb2c84-6242-4668-8f19-2c9f9156cd4f.png)

**Comment by anthony-ft** [comment]
Italics looks/sounds good. Appreciate the mockups :O
