### ISSUE TITLE
Basic info onboarding change

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#26]
- [x] Move onboarding to same page as bio/details
- [x] Add "(optional)" beside each title

**Comment by kfarwell** [comment]
Should this be page 1 or page 3?

**Comment by kfarwell** [comment]
![image](https://user-images.githubusercontent.com/4172356/132116461-916027dc-364c-49d5-bc96-93c2bc0fe839.png)

**Comment by kfarwell** [comment]
Back to two pages, split differently, both at the end of onboarding.

![image](https://user-images.githubusercontent.com/4172356/132118276-123e238c-6cca-4c8f-93e2-38df005f23f3.png)
![image](https://user-images.githubusercontent.com/4172356/132118289-149701c0-4dbe-4163-bcf0-52eb3145f18c.png)
