### ISSUE TITLE
Out of guests Guest List screen

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#28]
I like this a lot except please change "matches > guests". 

Terminology wise, I think matches are double waves/when people add as friend back after  wave, guests are people showing up on Guest List. Would you agree?

I still don't wanna use the term "matching/matches" publicly for now, its too date-y. "Matchmaking" is fine since it has more gamer connotations.

![image](https://user-images.githubusercontent.com/58100906/133140652-f7db7891-b3e0-430c-904b-51cba1ce7d9c.png)

**Comment by kfarwell** [comment]
Sure.
