### ISSUE TITLE
Notifications indicator and link - for Guest List

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#29]
Not clear where seeing who waved you is (takes 4 clicks away from guest list: Home, ROVR, Profiles, Notifications)

Can we put notifications-link at the top of the Guest List (help-text) and after you've finished waving (to see who's waved at you, visit your notifications (**link**))?

- [x] indicator on the button
- [x] also on the profile pic inside the menu
- [x] notification link on Guest List page **(do first)**

**Comment by kfarwell** [comment]
Added notifications link on guest list, only if the user has waves pending.

> takes 4 clicks away from guest list:
3 clicks for the record, you don't have to go home to open the ROVR menu.
