### ISSUE TITLE
More privacy options 

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#31]
Priority is the Just Me (it's been requested a few times, seems redundant, but ppl like to keep things on strictest privacy sometimes) - we don't need friends/mutual friends privacy for now, since bio info is limited.

- [x] Just me 

- [ ] #36

**Comment by kfarwell** [comment]
Added "just me" on dev, lmk if there are any settings where this shouldn't be an option or where this should be the default option.

**Comment by kfarwell** [comment]
Tracking "friends and mutual friends" in #36 & closing this one.
