### ISSUE TITLE
"You've got waves" weekly email

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#35]
Only if people have pending waves, and if they have not 1. passed accepted on the person 2. checked their guest list or 3. logged in since receiving the "someone waved at you email".

The 3 are in descending order of activity required - do you have a preference which to use? I'd say it's checking their guest list that counts as having checked their waves.

- [] Weekly email
- [] Weekly - "New friends" section. USERNAME added you as a friend, as part of the weekly email.

**Comment by kfarwell** [comment]
We shipped 1.2 a month ago ;)

**Comment by kfarwell** [comment]
@anthony-ft Would you like to write this digest email?

Apart from the email template, this feature is implemented.

**Comment by kfarwell** [comment]
Notification setting isn't working... reopening
