### ISSUE TITLE
Confirmation before visiting an external site

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#40]
For custom website URL link on profile.

The other links are fine though (everything except the custom website)

**Comment by kfarwell** [comment]
Nothing fancy but here we go.

![image](https://user-images.githubusercontent.com/4172356/141006905-3f676472-cb9e-47ef-af91-b84b915bd511.png)

**Comment by anthony-ft** [comment]
Looks good but we can cut second sentence it's too sketchy xD

**Comment by kfarwell** [comment]
@anthony-ft We can reword but it's good to (1) tell people why we're annoying them with this popup (security!) and (2) disclaim our responsibility for external sites.

Some inspiration...

Discord:
> HOLD UP
> Links are spoopy. This link goes to http://... Are you sure you want to go there?

Steam:
> Notice: You are leaving Steam.
> http://... is not an official Steam site.
>  Never enter your Steam password on an untrusted website. Any login form on an official Steam site will display “Valve Corp.” in green with a padlock icon in your browser’s address bar, as shown below: 
> ![image](https://user-images.githubusercontent.com/4172356/141041105-b3b287e6-cfac-41c2-a72c-104b29c808e8.png)

Facebook:
> Please be careful
> For the safety and privacy of your Facebook account, remember to never enter your password unless you're on the real Facebook web site. Also be sure to only download software from sites you trust. Learn more about keeping your account secure.
> http://...

Microsoft Office:
> Opening http://...
> Some files can contain viruses or otherwise be harmful to your computer.
> It is important to be certain that this file is from a trustworthy source.
> Would you like to open this file?

Adobe:
> This document is trying to connect to: http://...
> If you trust this site, choose Allow. If you do not trust this site, choose Block.

**Comment by anthony-ft** [comment]
Sounds good. I'd just reword the "don't blame us" (feels very antagonizing)
to something like, " Are you sure you want to visit [link]? This site is
not officially connected to ROVR - it might be sketchy!" is good.

Or, "You are leaving ROVR. Are you sure you want to visit [link]? It could
be sketchy!", any variation of these or the examples from other sites.
