### ISSUE TITLE
Updating interests and matchmaking weights

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#42]
Experimenting with matchmaking to improve people's guest lists:|
- [x] Increasing weight of Matching game to 15x (from 10x)
- [x] Reducing weight of Mutual invite to 20 (from 100x)
- [x] Increasing the weight of chosen default interests from 0.1x each to 10x (half the weight of a Custom Interest): 
- Social VR: Roleplaying
- Genre: Anime
- Creative: Art, Film/Video, Game Dev, Making VR Avatars, Making VR Worlds, Music, Streaming, Writing
- Gaming: MMO, eSports
- Life: Furry, Language Learning, LGBTQIA+, Sign Language, Student

- [x] Changes to interests formatting: 
- Creative --> Beginners, pros, and fans are all welcome!
- Genre --> Where you like to nerd out. 
- Custom Interests --> Input up to 15 things that make you you. > Input up to 15 things you love.
- (change position, put below input box) > Hit "tab" or "enter" to input multiple tags.

**Comment by kfarwell** [comment]
Looks like the weights we were looking at were out of date. Here is what we have now:
- Mutual inviter * 10
- Second degree inviter * 5
- Custom tags * 40
- Default tags * 0.1
- Wave * 30
- Friends * 5
- Groups * 20
- Games * 10

I've updated mutual inviter to *20 and games to *15, but let me know if you think we should stick to *10 for mutual inviter or make any other changes.
