### ISSUE TITLE
Making Custom Interests capitalization-agnostic for matchmaking

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#43]
Backporting capitalization-agnostic Custom Interests for matchmaking.

Future: 
- Manually link custom interests that are synonyms, or highly related
- Are we able to do something about symbols too?
- Integrate synonyms feature in Redis Search

**Comment by kfarwell** [comment]
Fixed, but I made a typo and deleted the psychology tag. :cry: 

A moment of silence.
