### ISSUE TITLE
Default profile pictures

### ISSUE THREAD

**Issue by kfarwell** [rovrlabs/rovr#45]
Provide some default pictures to choose from instead of uploading.

- [x] Profile pic selection in onboarding
- [x] Render profile pics (profiles, friends list, user menu)
- [x] Require invites to unlock pic categories

**Comment by kfarwell** [comment]
@anthony-ft We should explain this meme thing better. Are we going to repost memes? Do they need to be original? (If not, they should cite their source?)

And Discord DMs are a bit inconvenient - some users might not be on Discord, and there is some friction because they have to manually type in our name, send a friend request, ...maybe a simple file drop would be better.

**Comment by anthony-ft** [comment]
Hmmm that gets complicated, we can cut the meme stuff and just say, “with
each major update.”

If we want to keep the meme thing we can put up on our discord as an
informal way, or as an Easter egg info hover over on the site over invites?

“…or you can email us a SFW VR meme at ***@***.*** Don’t worry, we
won’t repost it (unless you want us to).”

Then we can ask for source and if they want attribution.

**Comment by kfarwell** [comment]
@anthony-ft Sounds good.

What if we give people 1 invite just for joining our Discord server? We can have a channel for people to post their ROVR usernames to redeem. Then all the profile pics can be unlocked (4 invites) without waiting for the next update.

**Comment by kfarwell** [comment]
How about a little newsletter incentive here too? Seeing as you're probably not going to know we gave you more invites if you're not subscribed anyway.

![Screenshot 2021-11-05 at 22-35-04 ROVR](https://user-images.githubusercontent.com/4172356/140585927-3abb685d-e117-449a-b4f4-01755d6c9042.png)

**Comment by anthony-ft** [comment]
I thought people were auto-subscribed to newsletter - is that separate from
updates? If not I'd ixnay that, newsletters too annoying.

"You will gain 3 more invites with each major update (roughly every month)."

"You can also get more invites by joining *our Discord server*."

I think the Discord idea is good, we definitely want a username drop like
VRLFP. 1 is too few - maybe 3, again, for verifying username on Discord.
We'll likely only have 1-2 more updates in closed beta right? (msging,
profile pics) so the more invites the better.

**Comment by kfarwell** [comment]
@anthony-ft This is our newsletter, just the ~monthly feature updates where we are giving out these invites already. I figure if someone isn't interested in that they're probably not going to be inviting people either, and they're not going to realize they have more invites if they're not getting the email where we tell them about it.
![Screenshot 2021-11-06 at 01-29-03 ROVR](https://user-images.githubusercontent.com/4172356/140593341-db97b800-24ab-4c93-87c5-22d065c30e2b.png)

I hate newsletters but ours isn't spammy and it's pretty important to us for retention. Right now ROVR doesn't do much, so without the newsletter letting people know that it does more things, most people are probably setting up their profile and never/rarely returning. And there are probably some people who automatically refuse emails whenever they sign up for something (myself included) but a little reminder that our newsletter exists might change their mind (after they've invited 3 people, they probably care about ROVR enough to be interested in the newsletter).

3 for Discord - sure.

**Comment by kfarwell** [comment]
@anthony-ft New help text:

If the user is subscribed to our emails:
> Want more invites? We'll be giving out more invites with each major update. (Keep an eye on your email!)
> 
> You can also get 3 extra invites by joining [our Discord server](https://rovrapp.com/discord).

If the user is **not** subscribed to our emails:
> Want more invites? We'll be giving out more invites with each major update. ([Subscribe to our emails](/settings#notifications) to know when this happens!)
> 
> You can also get 3 extra invites by joining [our Discord server](https://rovrapp.com/discord).

Do we want to increase the base invites to 10 with 1.3? Do we want to change any of this then?
