### ISSUE TITLE
Group display of interests

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#57]
- [x] Sorting group interests by popularity (# of members with the interest), instead of sorting the interests alphabetically
- [x] Contextual highlighting based on the user (shared interests highlighted, like when looking at someone else's profile)
- [x] Limiting interests shown to 5 or 10 (currently there is a high level of generic interests)

**Comment by kfarwell** [comment]
@anthony-ft 

> Limiting interests shown to 5 or 10

Right now we have up to 10 defaults and 5 customs. Often there are less than 5 customs in common.

Should it be 5 and 5?

**Comment by kfarwell** [comment]
We decided to have groups tag themselves manually, up to 3 default tags and 2 custom. :ballot_box_with_check:
