### ISSUE TITLE
Staying logged in on ROVR

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#60]
- [x] Option to stay logged in on a browser for one week or one month (preferable), etc.
- [x] Logout button -> destroys all sessions

**Comment by kfarwell** [comment]
Investigate staying logged in longer/forever for PWA

**Comment by kfarwell** [comment]
![image](https://user-images.githubusercontent.com/4172356/149032700-51847cd8-5f1a-49de-aa2a-b4d37f20c480.png)
**Unchecked:** current behaviour (session expires after 30 mins of inactivity or 24 hours regardless of activity), plus the session cookie is deleted when the browser is closed.
**Checked:** session expires after 30 days of inactivity or 365 days regardless of activity.

**Comment by kfarwell** [comment]
For added security to compensate for increased session lengths, the Logout button now logs out all of the user's sessions.
