### ISSUE TITLE
Wave email from new friend

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#64]
Get "You've got a wave!" email once someone adds you back as a friend

**Comment by kfarwell** [comment]
here's what the email looks like - @anthony-ft lmk if you want any changes:

* * *
**Subject:** `$user` waved back!

`$user` wants to meet you too.

[Send them a message] -> https://rovrapp.com/$user

**Comment by anthony-ft** [comment]
*This should show the best of both worlds, info of new friend + username in
the email preview. Can we rephrase to, *

*Subject: *You have a new friend on ROVR!

$user waved back - they want to meet you too!

[Send them a message] -> https://rovrapp.com/$user

**Comment by kfarwell** [comment]
:+1: Done
