### ISSUE TITLE
Homie mode update

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/rovr#78]
- [ ] Homie mode

- Green gradient on titles, buttons, outlines
- Sorted by last active
- Button in menu

- [ ] Updated menu order:

(Profile pic) -- either top or bottom
Browse
Homie Mode
Matches
Premium 

- [ ] Remove existing "you are now in homie mode" disclaimer

**Comment by kfarwell** [comment]
Wrong repo

**Comment by anthony-ft** [comment]
ono
